# This will build the application, send it to a Docker repository and ssh into the server to rebuild it

name: Bookble Continuous Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server_ssh.key
          chmod 600 ~/.ssh/server_ssh.key
          cat >>~/.ssh/config <<END
          Host bots-docker
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server_ssh.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}

      - name: Deploy Application
        run: ssh bots-docker 'cd ../ && cd /home/Olamileke/bots-docker && ./build.sh bookble'
